// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhzwholxmjolpinyxxsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoendob2x4bWpvbHBpbnl4eHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjcwNzgsImV4cCI6MjA1MDYwMzA3OH0.naC6NGBL-mtS1mIamQvHNR8uQnnB6Rh62rfrTIN_poI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);